CREATE OR REPLACE PROCEDURE GET_STUDENT_COURSE(
	COURSEID IN COURSE_TABLE.CID%TYPE,
	RET OUT SYS_REFCURSOR
)
AS
begin
  OPEN RET FOR 
  SELECT USER_TABLE.USERNAME, FNAME || ' ' || LNAME AS FULLNAME, EMAIL, COUNTRY, DOB, ADDRESU, OCCUPATION
  FROM USER_TABLE JOIN STUDENT_TABLE ON USER_TABLE.USERNAME = STUDENT_TABLE.USERNAME
  JOIN REGISTER_TABLE ON REGISTERS = STUDENT_TABLE.USERNAME
  WHERE REGISTERC = COURSEID;
end;
/
set serveroutput on;
DECLARE 
RET SYS_REFCURSOR;
USERNAME VARCHAR(15);
FULLNAME VARCHAR(30);
EMAIL VARCHAR(225);
COUNTRY VARCHAR(30);
DOB DATE;
ADDRESU VARCHAR(255);
OCCUPATION VARCHAR(30);
BEGIN
    GET_STUDENT_COURSE('000000015', RET);
    loop
        fetch RET into USERNAME, FULLNAME, EMAIL, COUNTRY, DOB, ADDRESU, OCCUPATION; -- and other columns if needed
        exit when RET%notfound;
        dbms_output.put_line(USERNAME || ' ' || FULLNAME ||' '|| EMAIL ||' '|| COUNTRY ||' '|| DOB ||' '|| ADDRESU ||' '|| OCCUPATION);
  end loop;
END;
/
CREATE OR REPLACE PROCEDURE GET_LEARNING_MATERIAL(
	PCOURSEID IN COURSE_TABLE.CID%TYPE,
	RET OUT SYS_REFCURSOR
)
AS
begin
  OPEN RET FOR 
  SELECT CONTENTID, AUTHOR, TYPEE
  FROM LEARNINGMATERIAL
  JOIN COURSE_TABLE ON COURSE_TABLE.CID = LEARNINGMATERIAL.COURSEID
  WHERE COURSE_TABLE.CID = PCOURSEID;
end;
/
set serveroutput on;
DECLARE 
RET SYS_REFCURSOR;
contentID   char(5);
Author      varchar(15);
Typee       varchar(255);
BEGIN
    GET_LEARNING_MATERIAL('000000015', RET);
    loop
        fetch RET into CONTENTID, AUTHOR, TYPEE; -- and other columns if needed
        exit when RET%notfound;
        dbms_output.put_line(CONTENTID|| ' ' || AUTHOR ||' '|| TYPEE);
  end loop;
END;
/
